directorio_archivo_backup_hashes = "/etc/backup_hashes_files"
alarmas_log = "/var/log/hips/alarmas.log"
prevencion_log = "/var/log/hips/prevención.log"
directorio_cuarentena = "/var/log/hips/cuarentena"
directorio_secure = "/var/log /secure"
directorio_messages = "/var/log/messages"
directorio_access_log = "/var/log/httpd/access.log"
directorio_maillog = "/var/log/maillog"
md5_tmp_dir = '/tmp/so2hipshashes.md5'
